###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID ictc-eda-be-9-ldap-1)
#  Generated on:      Mon Sep 15 11:41:49 2025
#  Design:            croc_chip
#  Command:           create_ccopt_clock_tree_spec -file ccopt_native.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Timing through the following pins was disabled by case analysis
# These pins are ignore skew pins
set_ccopt_property sink_type -pin i_croc_soc/i_croc/i_dmi_jtag/i_dmi_jtag_tap_i_dft_tck_mux/i_mux/A1 ignore
set_ccopt_property sink_type_reasons -pin i_croc_soc/i_croc/i_dmi_jtag/i_dmi_jtag_tap_i_dft_tck_mux/i_mux/A1 set_case_analysis

# The following pins are on the boundary of the STA clock network
# These pins are ignore skew pins
set_ccopt_property sink_type -pin pad_ref_clk_i/pad ignore
set_ccopt_property sink_type_reasons -pin pad_ref_clk_i/pad no_sdc_clock

# Pin offsets inferred from set_clock_latency assertions:
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_cs_registers_i/debug_ebreakm_o_reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_0__reg/CLK 0.216
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_12__reg/CLK 0.206
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_13__reg/CLK 0.234
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_14__reg/CLK 0.205
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_15__reg/CLK 0.279
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_16__reg/CLK 0.267
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_17__reg/CLK 0.246
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_18__reg/CLK 0.104
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_19__reg/CLK 0.198
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_1__reg/CLK 0.235
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_20__reg/CLK 0.293
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_21__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_22__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_23__reg/CLK 0.201
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_24__reg/CLK 0.289
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_25__reg/CLK 0.190
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_26__reg/CLK 0.217
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_27__reg/CLK 0.281
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_28__reg/CLK 0.275
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_29__reg/CLK 0.276
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_2__reg/CLK 0.199
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_30__reg/CLK 0.256
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_31__reg/CLK 0.204
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_3__reg/CLK 0.187
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_4__reg/CLK 0.230
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_5__reg/CLK 0.193
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_i_6__reg/CLK 0.213
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_controller_i_instr_valid_i_reg/CLK 0.281
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_id_stage_i_id_fsm_q_reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_load_store_unit_i_ls_fsm_cs_0__reg/CLK 0.287
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_load_store_unit_i_ls_fsm_cs_1__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_core_wrap/i_ibex_load_store_unit_i_ls_fsm_cs_2__reg/CLK 0.287
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_dmi_jtag/i_dmi_cdc_i_cdc_req/i_dst/async_ack_o_reg/CLK 0.313
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_dmi_jtag/td_o_reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_106__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_113__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_120__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_127__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_134__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_141__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_148__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_155__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_15__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_162__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_169__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_176__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_183__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_190__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_197__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_1__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_204__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_211__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_218__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_22__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_29__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_36__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_43__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_50__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_57__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_64__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_71__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_78__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_85__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_8__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_92__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_gpio/i_reg_file_reg2hw_99__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_timer/counter_lo_i_target_reached_o_reg/CLK 0.034
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_timer/s_cfg_hi_reg_2__reg/CLK 0.352
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_timer/s_cfg_lo_reg_2__reg/CLK 0.368
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_timer/s_cfg_lo_reg_31__reg/CLK 0.300
set_ccopt_property insertion_delay -pin i_croc_soc/i_croc/i_uart/i_apb_uart_UART_IIC_IIR_0__reg/CLK 0.300

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk_i true
set_ccopt_property cts_is_sdc_clock_root -pin jtag_tck_i true
set_ccopt_property cts_is_sdc_clock_root -pin ref_clk_i true

# Clocks present at pin clk_i
#   clk_sys (period 10.000ns) in timing_config func_mode_ideal_wc([/ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc])
#   clk_sys (period 10.000ns) in timing_config func_mode_ideal_bc([/ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc])
create_ccopt_clock_tree -name clk_sys -source clk_i -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay_wc -early -clock_tree clk_sys 0.200

set_ccopt_property target_max_trans_sdc -delay_corner delay_wc -late -clock_tree clk_sys 0.200
set_ccopt_property source_driver -clock_tree clk_sys {sg13g2_IOPadOut16mA/c2p sg13g2_IOPadOut16mA/pad}
# Clock period setting for source pin of clk_sys
set_ccopt_property clock_period -pin clk_i 10

# Clocks present at pin ref_clk_i
#   clk_rtc (period 50.000ns) in timing_config func_mode_ideal_wc([/ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc])
#   clk_rtc (period 50.000ns) in timing_config func_mode_ideal_bc([/ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc])
create_ccopt_clock_tree -name clk_rtc -source ref_clk_i -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay_wc -early -clock_tree clk_rtc 0.200

set_ccopt_property target_max_trans_sdc -delay_corner delay_wc -late -clock_tree clk_rtc 0.200
set_ccopt_property source_driver -clock_tree clk_rtc {sg13g2_IOPadOut16mA/c2p sg13g2_IOPadOut16mA/pad}
# Clock period setting for source pin of clk_rtc
set_ccopt_property clock_period -pin ref_clk_i 50

# Clocks present at pin jtag_tck_i
#   clk_jtg (period 20.000ns) in timing_config func_mode_ideal_wc([/ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc])
#   clk_jtg (period 20.000ns) in timing_config func_mode_ideal_bc([/ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc])
create_ccopt_clock_tree -name clk_jtg -source jtag_tck_i -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay_wc -early -clock_tree clk_jtg 0.200

set_ccopt_property target_max_trans_sdc -delay_corner delay_wc -late -clock_tree clk_jtg 0.200
set_ccopt_property source_driver -clock_tree clk_jtg {sg13g2_IOPadOut16mA/c2p sg13g2_IOPadOut16mA/pad}
# Clock period setting for source pin of clk_jtg
set_ccopt_property clock_period -pin jtag_tck_i 20

# Skew group to balance non generated clock:clk_jtg in timing_config:func_mode_ideal_wc (sdc /ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc)
create_ccopt_skew_group -name clk_jtg/func_mode_ideal_wc -sources jtag_tck_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_jtg/func_mode_ideal_wc true
set_ccopt_property extracted_from_clock_name -skew_group clk_jtg/func_mode_ideal_wc clk_jtg
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_jtg/func_mode_ideal_wc func_mode_ideal_wc
set_ccopt_property extracted_from_delay_corners -skew_group clk_jtg/func_mode_ideal_wc delay_wc

# Skew group to balance non generated clock:clk_rtc in timing_config:func_mode_ideal_wc (sdc /ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc)
create_ccopt_skew_group -name clk_rtc/func_mode_ideal_wc -sources ref_clk_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_rtc/func_mode_ideal_wc true
set_ccopt_property extracted_from_clock_name -skew_group clk_rtc/func_mode_ideal_wc clk_rtc
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_rtc/func_mode_ideal_wc func_mode_ideal_wc
set_ccopt_property extracted_from_delay_corners -skew_group clk_rtc/func_mode_ideal_wc delay_wc

# Skew group to balance non generated clock:clk_sys in timing_config:func_mode_ideal_wc (sdc /ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc)
create_ccopt_skew_group -name clk_sys/func_mode_ideal_wc -sources clk_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_sys/func_mode_ideal_wc true
set_ccopt_property extracted_from_clock_name -skew_group clk_sys/func_mode_ideal_wc clk_sys
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_sys/func_mode_ideal_wc func_mode_ideal_wc
set_ccopt_property extracted_from_delay_corners -skew_group clk_sys/func_mode_ideal_wc delay_wc

# Skew group to balance non generated clock:clk_jtg in timing_config:func_mode_ideal_bc (sdc /ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc)
create_ccopt_skew_group -name clk_jtg/func_mode_ideal_bc -sources jtag_tck_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_jtg/func_mode_ideal_bc true
set_ccopt_property extracted_from_clock_name -skew_group clk_jtg/func_mode_ideal_bc clk_jtg
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_jtg/func_mode_ideal_bc func_mode_ideal_bc
set_ccopt_property extracted_from_delay_corners -skew_group clk_jtg/func_mode_ideal_bc delay_bc

# Skew group to balance non generated clock:clk_rtc in timing_config:func_mode_ideal_bc (sdc /ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc)
create_ccopt_skew_group -name clk_rtc/func_mode_ideal_bc -sources ref_clk_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_rtc/func_mode_ideal_bc true
set_ccopt_property extracted_from_clock_name -skew_group clk_rtc/func_mode_ideal_bc clk_rtc
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_rtc/func_mode_ideal_bc func_mode_ideal_bc
set_ccopt_property extracted_from_delay_corners -skew_group clk_rtc/func_mode_ideal_bc delay_bc

# Skew group to balance non generated clock:clk_sys in timing_config:func_mode_ideal_bc (sdc /ictc/student_data/vantruong/final_pj/fn_prj_here/flowspd/pd1/02timingclean.dat/libs/mmmc/constraints.sdc)
create_ccopt_skew_group -name clk_sys/func_mode_ideal_bc -sources clk_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_sys/func_mode_ideal_bc true
set_ccopt_property extracted_from_clock_name -skew_group clk_sys/func_mode_ideal_bc clk_sys
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_sys/func_mode_ideal_bc func_mode_ideal_bc
set_ccopt_property extracted_from_delay_corners -skew_group clk_sys/func_mode_ideal_bc delay_bc


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

